name: Obfuscate BPB Worker

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"  # Daily at 1AM

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - run: npm install -g javascript-obfuscator

      - name: Fetch source file
        run: wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      - name: Obfuscate code
        run: >
          javascript-obfuscator origin.js --output _worker.js
          --compact --control-flow-flattening
          --control-flow-flattening-threshold 1
          --dead-code-injection --dead-code-injection-threshold 1
          --identifier-names-generator hexadecimal
          --rename-globals --string-array
          --string-array-encoding rc4
          --string-array-threshold 1
          --transform-object-keys
          --unicode-escape-sequence

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":arrow_up: update latest bpb panel"
